backend:
  name: github
  repo: Jaspero/exo
  branch: master
  base_url: https://us-central1-exo-brands.cloudfunctions.net/oAuth
  auth_endpoint: /oauth/auth
publish_mode: editorial_workflow

# Media files will be stored in the repo under docs/uploads
media_folder: "public/uploads"

# The src attribute for uploaded media will begin with /uploads
public_folder: "/uploads"

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'docs/collections/blog'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }


  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Home'
        name: 'home'
        file: 'docs/collections/pages/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'home' }
          - { label: 'Layout', name: 'title', widget: 'hidden', default: 'home' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
