backend:
  name: github
  repo: Jaspero/exo
  branch: master
  base_url: https://us-central1-exo-brands.cloudfunctions.net/
  auth_endpoint: /oauth/auth
publish_mode: editorial_workflow

# Media files will be stored in the repo under docs/uploads
media_folder: "public/uploads"

# The src attribute for uploaded media will begin with /uploads
public_folder: "/uploads"

animation: &animation
  label: "Animation"
  name: "animation"
  widget: "select"
  options:
    - { label: "None", value: "none" }
    - { label: "Fade In", value: "fade-in" }
    - { label: "Fade In From Top", value: "fade-in-from-top" }
    - { label: "Fade In From Bottom", value: "fade-in-from-bottom" }
    - { label: "Fade In From Left", value: "fade-in-from-left" }
    - { label: "Fade In From Right", value: "fade-in-from-right" }
  default: ["none"]

# Reusable blocks for all of the pages
blocks: &blocks
  label: "Blocks"
  name: "blocks"
  widget: "list"
  types:
    - label: "Image R"
      name: "imageR"
      widget: "object"
      fields:
        - <<: *animation
        - { label: "Title", name: "title", widget: "string", required: false }
        - { label: "Image", name: "image", widget: "image", required: false }
        - { label: "content", name: "content", widget: "markdown", required: false }
        - { label: "Below Image", name: "belowImg", widget: "image", required: false }

    - label: "Image L"
      name: "imageL"
      widget: "object"
      fields:
        - <<: *animation
        - { label: "Title", name: "title", widget: "string", required: false }
        - { label: "Image", name: "image", widget: "image", required: false }
        - { label: "content", name: "content", widget: "markdown", required: false }
        - { label: "Below Image", name: "belowImg", widget: "image", required: false }

    - label: "Image Large"
      name: "imageLarge"
      widget: "object"
      fields:
        - <<: *animation
        - { label: "Image", name: "image", widget: "image", required: false }

    - label: "Logo Block"
      name: "textImgBlock"
      widget: "object"
      fields:
        - <<: *animation
        - { label: "Image", name: "image", widget: "image", required: false }
        - { label: "content", name: "content", widget: "markdown", required: false }

    - label: "Image Shadow R"
      name: "imageShadowR"
      widget: "object"
      fields:
        - <<: *animation
        - { label: "Title", name: "title", widget: "string", required: false }
        - { label: "Image", name: "image", widget: "image", required: false }
        - { label: "content", name: "content", widget: "markdown", required: false }
        - { label: "Link", name: "link", widget: "string", required: false }
        - { label: "Button Title", name: "buttonTitle", widget: "string", required: false }


    - label: "Image Full"
      name: "imageFull"
      widget: "object"
      fields:
        - <<: *animation
        - { label: "Image", name: "image", widget: "image", required: false }

    - label: "Image Full Button"
      name: "imageFullButton"
      widget: "object"
      fields:
        - <<: *animation
        - { label: "Image", name: "image", widget: "image", required: false }
        - { label: "Title", name: "title", widget: "string", required: false }
        - { label: "Link", name: "link", widget: "string", required: false }
        - { label: "Button Title", name: "buttonTitle", widget: "string", required: false }

    - label: "Text Block"
      name: "textBlock"
      widget: "object"
      fields:
        - <<: *animation
        - { label: "Title", name: "title", widget: "string", required: false }
        - { label: "content", name: "content", widget: "markdown", required: false }

    - label: "Event Image Block"
      name: "eventImageBlock"
      widget: "object"
      fields:
        - <<: *animation
        - { label: "Image", name: "image", widget: "image", required: false }
        - { label: "Title", name: "title", widget: "string", required: false }
        - { label: "content", name: "content", widget: "markdown", required: false }

    - label: "Image Right Button"
      name: "imageRightButton"
      widget: "object"
      fields:
        - <<: *animation
        - { label: "Title", name: "title", widget: "string", required: false }
        - { label: "Image", name: "image", widget: "image", required: false }
        - { label: "content", name: "content", widget: "markdown", required: false }
        - { label: "Below Image", name: "belowImg", widget: "image", required: false }

    - label: "Image Left Button"
      name: "imageLeftButton"
      widget: "object"
      fields:
        - <<: *animation
        - { label: "Title", name: "title", widget: "string", required: false }
        - { label: "Image", name: "image", widget: "image", required: false }
        - { label: "content", name: "content", widget: "markdown", required: false }
        - { label: "Below Image", name: "belowImg", widget: "image", required: false }

    - label: "March Events"
      name: "marchEvents"
      widget: "object"
      fields:
        - <<: *animation
        - { label: "Title", name: "title", widget: "string", required: false }
        - { label: "content", name: "content", widget: "markdown", required: false }
        - { label: "Event Done", name: "eventDone", widget: "string", required: false }
        - { label: "Event Canceled", name: "eventDone", widget: "string", required: false }
        - { label: "Image", name: "image", widget: "image", required: false }

meta: &meta
  label: "Meta"
  name: "meta"
  widget: "object"
  fields:
    - { label: "Title", name: "title", widget: "string", required: false }
    - { label: "Description", name: "description", widget: "text", required: false }
    - { label: "Keywords", name: "keywords", widget: "string", required: false }

showcase: &showcase
  label: "Showcase"
  name: "showcase"
  widget: "object"
  fields:
    - { label: "Title", name: "title", widget: "text", required: false }
    - { label: "Subtitle", name: "subTitle", widget: "string", required: false }
    - { label: "Background", name: "background", widget: "file", allow_multiple: false }

itemMenu: &itemMenu
  label: "Categories"
  name: "categories"
  widget: "list"
  fields:
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Subtitle", name: "subTitle", widget: "string", required: false }
    - { label: "Price", name: "price", widget: "string", required: false }
    - label: "Items"
      name: "items"
      widget: "list"
      fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Subtitle", name: "subTitle", widget: "string", required: false }
        - { label: "Price", name: "price", widget: "string", required: false }
        - { label: "Image", name: "image", widget: "image", required: false }

pageDefault: &pageDefault
  - <<: *showcase
  - <<: *meta
  - <<: *blocks

pageLight: &pageLight
  - <<: *showcase
  - <<: *meta

collectionPage: &collectionPage
  - <<: *showcase
  - <<: *meta
  - { label: "First Segment", name: "firstSegment", widget: "text", required: false }

collections:
  - name: "blog"
    label: "Posts"
    folder: "public/collections/blog"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image alternative description", name: "alt", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "products"
    label: "Products"
    folder: "public/collections/shop"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Featured Image"
        name: "image"
        widget: "image"
        hint: "This is displayed on the shop page"
      - label: "Display Image"
        name: "displayImage"
        widget: "image"
        hint: "This is displayed on the single product page"
      - label: "Showcase Gallery"
        name: "galleryImages"
        widget: "list"
        fields:
          - {label: Image, name: image, widget: image}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Product Description", name: "productDescription", widget: "markdown" }
      - { label: "Additional Info", name: "additionalInfo", widget: "markdown" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Shopify Product ID", name: "productId", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "events"
    label: "Events"
    folder: "public/collections/events"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - label: "Featured Image"
        name: "image"
        widget: "image"
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "news"
    label: "News"
    folder: "public/collections/news"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - label: "Featured Image"
        name: "image"
        widget: "image"
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    extension: "json"
    format: "json"
    editor:
      preview: false
    files:
      - label: "Home"
        name: "home"
        file: "public/collections/pages/home.json"
        fields: *pageDefault
      - label: "Nail Bar"
        name: "nail"
        file: "public/collections/pages/nail.json"
        fields: *pageDefault
      - label: "Lounge"
        name: "lounge"
        file: "public/collections/pages/lounge.json"
        fields: *pageDefault
      - label: "Exo Events"
        name: "exoEvents"
        file: "public/collections/pages/exoEvents.json"
        fields: *pageDefault
      - label: "Contact"
        name: "contact"
        file: "public/collections/pages/contact.json"
        fields:
          - <<: *showcase
          - <<: *meta
          - { label: "First Segment", name: "firstSegment", widget: "markdown", required: false }
          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "text" }
              - { label: "Address", name: "address", widget: "text" }
              - { label: "Phone", name: "phone", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
          - label: "Get in Touch"
            name: "getInTouch"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "text" }
              - { label: "Lounge", name: "lounge", widget: "string" }
              - { label: "Nail Bar", name: "nailBar", widget: "string" }
              - { label: "Events", name: "events", widget: "string" }
              - { label: "Press", name: "press", widget: "string" }
          - label: "Visit Us"
            name: "visitUs"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "text" }
              - label: "Lounge"
                name: "lounge"
                widget: "object"
                fields:
                  - { label: "Monday", name: "monday", widget: "string" }
                  - { label: "Tuesday", name: "tuesday", widget: "string" }
                  - { label: "Wednesday", name: "wednesday", widget: "string" }
                  - { label: "Thursday", name: "thursday", widget: "string" }
                  - { label: "Friday", name: "friday", widget: "string" }
                  - { label: "Saturday", name: "saturday", widget: "string" }
                  - { label: "Sunday", name: "sunday", widget: "string" }
              - label: "Nail Bar"
                name: "nailBar"
                widget: "object"
                fields:
                  - { label: "Monday", name: "monday", widget: "string" }
                  - { label: "Tuesday", name: "tuesday", widget: "string" }
                  - { label: "Wednesday", name: "wednesday", widget: "string" }
                  - { label: "Thursday", name: "thursday", widget: "string" }
                  - { label: "Friday", name: "friday", widget: "string" }
                  - { label: "Saturday", name: "saturday", widget: "string" }
                  - { label: "Sunday", name: "sunday", widget: "string" }
          - label: "Address"
            name: "address"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Latitude", name: "lat", widget: "number" }
              - { label: "Longitude", name: "lng", widget: "number" }
      - label: "Blog"
        name: "blog"
        file: "public/collections/pages/blog.json"
        fields: *collectionPage
      - label: "Events"
        name: "events"
        file: "public/collections/pages/events.json"
        fields: *pageLight
      - label: "News"
        name: "news"
        file: "public/collections/pages/news.json"
        fields: *collectionPage
      - label: "Shop"
        name: "shop"
        file: "public/collections/pages/shop.json"
        fields: *pageLight
      - label: "Locations"
        name: "locations"
        file: "public/collections/pages/locations.json"
        fields: *pageLight
      - name: "loungeMenu"
        label: "Lounge Menu"
        file: "public/collections/pages/lounge-menu.json"
        fields:
          - <<: *showcase
          - <<: *meta
          - <<: *itemMenu
      - name: "nailBarMenu"
        label: "Nail Bar Menu"
        file: "public/collections/pages/nail-bar-menu.json"
        fields:
          - <<: *showcase
          - <<: *meta
          - <<: *itemMenu
