backend:
  name: github
  repo: Jaspero/exo
  branch: master
  base_url: https://us-central1-exo-brands.cloudfunctions.net/
  auth_endpoint: /oauth/auth
publish_mode: editorial_workflow

# Media files will be stored in the repo under docs/uploads
media_folder: "public/uploads"

# The src attribute for uploaded media will begin with /uploads
public_folder: "/uploads"

# Reusable blocks for all of the pages
blocks: &blocks
  label: "Blocks"
  name: "blocks"
  widget: "list"
  types:
    - label: "Image R"
      name: "imageR"
      widget: "object"
      fields:
        - { label: "Title", name: "title", widget: "string", required: false }
        - { label: "Image", name: "image", widget: "image", required: false }
        - { label: "content", name: "content", widget: "markdown", required: false }
        - { label: "Below Image", name: "belowImg", widget: "image", required: false }

    - label: "Image L"
      name: "imageL"
      widget: "object"
      fields:
        - { label: "Title", name: "title", widget: "string", required: false }
        - { label: "Image", name: "image", widget: "image", required: false }
        - { label: "content", name: "content", widget: "markdown", required: false }
        - { label: "Below Image", name: "belowImg", widget: "image", required: false }

    - label: "Image Large"
      name: "imageLarge"
      widget: "object"
      fields:
        - { label: "Image", name: "image", widget: "image", required: false }

    - label: "Logo Block"
      name: "textImgBlock"
      widget: "object"
      fields:
        - { label: "Image", name: "image", widget: "image", required: false }
        - { label: "content", name: "content", widget: "markdown", required: false }

    - label: "Image Shadow R"
      name: "imageShadowR"
      widget: "object"
      fields:
        - { label: "Title", name: "title", widget: "string", required: false }
        - { label: "Image", name: "image", widget: "image", required: false }
        - { label: "content", name: "content", widget: "markdown", required: false }

    - label: "Image Full"
      name: "imageFull"
      widget: "object"
      fields:
        - { label: "Image", name: "image", widget: "image", required: false }

    - label: "Image Full Button"
      name: "imageFullButton"
      widget: "object"
      fields:
        - { label: "Image", name: "image", widget: "image", required: false }
        - { label: "Title", name: "title", widget: "string", required: false }

    - label: "Text Block"
      name: "textBlock"
      widget: "object"
      fields:
        - { label: "Title", name: "title", widget: "string", required: false }
        - { label: "content", name: "content", widget: "markdown", required: false }

    - label: "Event Image Block"
      name: "eventImageBlock"
      widget: "object"
      fields:
        - { label: "Image", name: "image", widget: "image", required: false }
        - { label: "Title", name: "title", widget: "string", required: false }
        - { label: "content", name: "content", widget: "markdown", required: false }

meta: &meta
  label: "Meta"
  name: "meta"
  widget: "object"
  fields:
    - { label: "Title", name: "title", widget: "string", required: false }
    - { label: "Description", name: "description", widget: "text", required: false }
    - { label: "Keywords", name: "keywords", widget: "string", required: false }

pageDefault: &pageDefault
  - { label: "Showcase Title", name: "showcaseTitle", widget: "string" }
  - { label: "Showcase Background", name: "showcaseBackground", widget: "file", allow_multiple: false }
  - <<: *meta
  - <<: *blocks

pageLight: &pageLight
  - { label: "Showcase Title", name: "showcaseTitle", widget: "string" }
  - { label: "Showcase Background", name: "showcaseBackground", widget: "file", allow_multiple: false }
  - <<: *meta

collections:
  - name: "blog"
    label: "Posts"
    folder: "public/collections/blog"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image alternative description", name: "alt", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "products"
    label: "Products"
    folder: "public/collections/shop"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Featured Image"
        name: "image"
        widget: "image"
      - label: "Showcase Gallery"
        name: "galleryImages"
        widget: "list"
        fields:
          - {label: Image, name: image, widget: image}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Product Description", name: "productDescription", widget: "markdown" }
      - { label: "Additional Info", name: "additionalInfo", widget: "markdown" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "events"
    label: "Events"
    folder: "public/collections/events"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - label: "Featured Image"
        name: "image"
        widget: "image"
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "news"
    label: "News"
    folder: "public/collections/news"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - label: "Featured Image"
        name: "image"
        widget: "image"
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    extension: "json"
    format: "json"
    editor:
      preview: false
    files:
      - label: "Home"
        name: "home"
        file: "public/collections/pages/home.json"
        fields: *pageDefault
      - label: "Nail Bar"
        name: "nail"
        file: "public/collections/pages/nail.json"
        fields: *pageDefault
      - label: "Lounge"
        name: "lounge"
        file: "public/collections/pages/lounge.json"
        fields: *pageDefault
      - label: "Contact"
        name: "contact"
        file: "public/collections/pages/contact.json"
        fields: *pageLight
      - label: "Blog"
        name: "blog"
        file: "public/collections/pages/blog.json"
        fields: *pageLight
      - label: "Events"
        name: "events"
        file: "public/collections/pages/events.json"
        fields: *pageLight
      - label: "News"
        name: "news"
        file: "public/collections/pages/news.json"
        fields: *pageLight
      - label: "Shop"
        name: "shop"
        file: "public/collections/pages/shop.json"
        fields: *pageLight
