backend:
  name: github
  repo: Jaspero/exo
  branch: master
  base_url: https://us-central1-exo-brands.cloudfunctions.net/
  auth_endpoint: /oauth/auth
publish_mode: editorial_workflow

# Media files will be stored in the repo under docs/uploads
media_folder: "public/uploads"

# The src attribute for uploaded media will begin with /uploads
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "public/collections/blog"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image alternative description", name: "alt", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }


  - name: "products"
    label: "Products"
    folder: "public/collections/shop"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - {label: "Description", name: "description", widget: "markdown"}
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
      - label: "Showcase Gallery"
        name: "galleryImages"
        widget: "list"
        fields:
          - {label: Image, name: image, widget: image}
      - {label: "Product Description", name: "product description", widget: "markdown"}
      - {label: "Additional Info", name: "additional info", widget: "markdown"}


  - name: "events"
    label: "Events"
    folder: "public/collections/events"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - label: "Featured Image"
        name: "image"
        widget: "image"


  - name: "news"
    label: "News"
    folder: "public/collections/news"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }

  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - label: "Home"
        name: "home"
        file: "public/collections/pages/home.md"
        fields:
          - { label: "Showcase Title", name: "showcaseTitle", widget: "string" }
          - { label: "Showcase Background", name: "showcaseBackground", widget: "string", allow_multiple: false }
          - label: "Meta"
            name: "meta"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Keywords", name: "keywords", widget: "string" }
          - label: "Blocks"
            name: "blocks"
            widget: "list"
            types:
              - label: "Block Image R"
                name: "blockImageR"
                widget: "object"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "content", name: "content", widget: "markdown" }
              - label: "Block Image L"
                  name: "blockImageR"
                  widget: "object"
                  fields:
                    - { label: "Title", name: "title", widget: "string" }
                    - { label: "Image", name: "image", widget: "image" }
                    - { label: "content", name: "content", widget: "markdown" }
