backend:
  name: github
  repo: @jaspero/exo
  branch: master
publish_mode: editorial_workflow

# Media files will be stored in the repo under docs/uploads
media_folder: "docs/uploads"

# The src attribute for uploaded media will begin with /uploads
public_folder: "/uploads"
